### ISSUE TITLE
도메인 주도 설계 원칙 및 코드 최적화를 위한 리팩토링

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/mt-web#38]
### Describe

코드베이스의 품질과 유지보수성을 지속적으로 향상시키기 위해, 도메인 주도 설계(DDD) 원칙을 기반으로 리팩토링을 진행합니다.

### Tasks

- [ ] DDD 원칙에 따른 코드 구조 변경
- [ ] 중복 및 사용하지 않는 코드 제거
- [x] 코드 문서화 강화(주석)
